### PR TITLE
Add webhippie/elasticsearch:7.10

### PR DESCRIPTION
**Pull request by DeepDiver1975**

### CODE REVIEW

**Comment by tboerger** [comment]
Looks like I got to migrate the repo to a private Drone instance first... Running into Docker Hub rate limit and the arm32v6 runner is also broken :(

**Comment by DeepDiver1975** [comment]
>  arm32v6

is not supported with elastic ... I removed it.
But actually this is only related to the bundled jdk ... I can work on that if needed ....

**Comment by DeepDiver1975** [comment]
> Looks like I got to migrate the repo to a private Drone instance first... Running into Docker Hub rate limit

anything I can help out with?

**Comment by tboerger** [comment]
Nothing you can help with, I need to setup a private instance.

**Comment by tboerger** [comment]
Thanks for your effor, it's replaced by https://github.com/dockhippie/elasticsearch/pull/6. If you need this exact version feel free to open another PR, this one should be much easier :)

**Pull request closed without merging**
